"use client"

import React, { useState } from 'react';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';
import ProtfolioDetails from './ProtfolioDetails';



const MyTab = () => {


    const Portfolio = [
        {
            "_id": "1",
            "image": "https://i.ibb.co.com/3WWR74S/Image-7.png",
            "title": "Website Design for SIEM Platform",
            "typeOfBusiness": "Corporate, Creative",
            "relatedPictures3": ["siem_pic1.jpg", "siem_pic2.jpg", "siem_pic3.jpg"],
            "description": "The Security Information and Event Management (SIEM) platform we worked on was designed to streamline data security and enhance event monitoring capabilities for large enterprises. The platform consolidates logs, alerts, and security events from various sources, enabling users to monitor and manage potential threats in real-time. A crucial aspect of SIEM systems is their ability to provide actionable insights from massive volumes of data. Our goal was to modernize the user interface to make the SIEM platform more user-friendly while maintaining the complex functionalities needed for security professionals. This required striking a balance between simplicity and depth, ensuring users could efficiently navigate through data without being overwhelmed. The platform also had to meet compliance and regulatory requirements, which added another layer of complexity to the design. The design needed to integrate seamlessly with the backend architecture, handling large datasets and providing a smooth experience. In a fast-paced world where security is of utmost importance, having a user-centric SIEM platform significantly reduces the time it takes to detect and respond to threats, ultimately reducing the risk to businesses.",

            "problems": "One of the main problems with the existing SIEM platform was the outdated interface, which made it difficult for users to navigate and interpret large amounts of data. The platform’s performance was also a concern, as it struggled to keep up with the real-time demands of modern security environments. The UI was cluttered with too much information, and the lack of organization often led to confusion, slowing down the response time to critical security events. Additionally, there were compatibility issues with newer data sources, as the platform was not designed to handle the influx of diverse logs from multiple modern systems. This significantly impacted the platform's effectiveness, as users needed more time to manually configure it for every new data source. In the era of increasing cybersecurity threats, having a slow and ineffective SIEM platform puts organizations at a higher risk of attacks, as they may miss crucial alerts. Furthermore, compliance with modern regulatory standards was a problem, as the platform did not support real-time compliance monitoring, which is now a requirement for most organizations handling sensitive data.",

            "challenges": "One of the major challenges was modernizing the user interface without compromising the complexity and depth of the SIEM platform's functionality. The SIEM system processes and monitors vast amounts of data in real-time, which means that even the smallest changes in design can have a huge impact on user experience and system performance. Designing a UI that is both visually appealing and functional for IT security professionals required a deep understanding of their workflows and the critical tasks they perform. Another challenge was improving system performance to handle the ever-increasing data flow from modern IT infrastructures. We also had to ensure that the platform remained compliant with various industry regulations, which involved incorporating real-time compliance monitoring features without cluttering the UI or making the system more difficult to use. Moreover, the platform needed to be scalable to accommodate the growing needs of businesses as they expand their IT infrastructure. This involved creating a modular design that could easily be adapted to different types of businesses and security environments.",

            "ourSolution": "Our solution was to adopt a user-centered design approach, focusing on creating a clean, intuitive interface while ensuring the underlying complexity of the SIEM platform remained accessible to advanced users. We implemented a dashboard that provided an overview of critical metrics, allowing users to quickly identify potential security threats without getting bogged down in unnecessary details. The new design also incorporated filtering and search functionalities that allowed users to customize their views based on their specific needs, thus improving usability and reducing the cognitive load on security teams. To address performance issues, we optimized the backend to handle larger datasets and incorporated real-time data processing capabilities, ensuring that the platform could keep up with the fast-paced nature of modern security environments. We also made the platform more modular, allowing for easier integration with new data sources, which enhanced its flexibility. Finally, we ensured that the platform was compliant with modern regulatory requirements by integrating real-time compliance monitoring features. This helped businesses stay ahead of potential compliance issues, reducing their legal risk. Ultimately, our solution improved the overall efficiency and effectiveness of the SIEM platform, allowing businesses to respond to threats more quickly and with greater confidence."
        }, {
            "_id": "2",
            "image": "https://i.ibb.co.com/rp3Ksft/Image-8.png",
            "title": "Online Doctor & Medicine Delivery App",
            "typeOfBusiness": "Business, Startup",
            "relatedPictures3": ["medicine_pic1.jpg", "medicine_pic2.jpg", "medicine_pic3.jpg"],
            "description": "In today’s fast-paced world, convenience and accessibility in healthcare are more important than ever. The Online Doctor & Medicine Delivery App was designed to address these needs, providing users with a platform to consult doctors online and order medications directly from pharmacies. The app bridges the gap between traditional healthcare and modern technology, offering real-time access to medical professionals and prescription services at the touch of a button. The aim was to provide a seamless user experience, enabling patients to manage their health without having to visit physical clinics or pharmacies. By integrating features such as video consultations, electronic prescriptions, and medication delivery tracking, the app offers a comprehensive solution for modern-day healthcare needs. This is particularly beneficial for elderly or mobility-restricted patients who may find it difficult to travel. Furthermore, the platform supports both one-time consultations and ongoing healthcare management, allowing users to maintain long-term relationships with healthcare providers. As the healthcare industry increasingly shifts toward digital solutions, this app offers a way for businesses to adapt to the changing landscape and meet the demands of a tech-savvy audience.",

            "problems": "Before this app, one of the biggest problems faced by users was the lack of reliable platforms that provided both medical consultations and medication delivery in one place. Patients often had to juggle between different services—one for consulting a doctor and another for getting their prescriptions filled. This fragmented approach created inefficiencies and, in some cases, delayed treatment. Additionally, rural areas and underserved communities faced a more significant challenge due to the limited availability of healthcare providers and pharmacies. For many, accessing a doctor was not only expensive but also time-consuming, requiring long travel distances. The COVID-19 pandemic further exacerbated this problem, with many people avoiding hospitals and clinics due to fear of infection. A unified platform that could provide medical consultations and deliver medications became a necessity, especially during such global health crises. Furthermore, many existing platforms did not provide a good user experience, making it difficult for older users or those unfamiliar with technology to navigate. This usability issue, combined with the lack of trust in online healthcare services, posed significant barriers to widespread adoption.",

            "challenges": "The primary challenge in this project was integrating two complex services—telemedicine and medicine delivery—into a single, cohesive platform. Each service comes with its own set of technical and regulatory requirements, which made combining them a challenging task. For example, telemedicine platforms need to comply with privacy and data protection laws, such as HIPAA in the U.S., to ensure that sensitive patient information is securely stored and transmitted. On the other hand, the medicine delivery service needed to integrate with various pharmacies, which required building APIs for inventory management, prescription verification, and tracking systems. Another challenge was creating an intuitive user interface that catered to a diverse user base, including elderly individuals and those with limited technological literacy. Balancing advanced features like video consultations, live chats, and prescription uploads with a simple, easy-to-use design was a delicate task. We also had to address logistical challenges, such as ensuring timely delivery of medications, especially for life-saving drugs that patients rely on daily. Additionally, we needed to build a scalable infrastructure that could handle a high volume of users, particularly during peak times, like flu seasons or pandemic surges.",

            "ourSolution": "Our solution was to develop a fully integrated app that combined telemedicine and medication delivery services into one unified platform. We started by conducting extensive user research to understand the pain points of different user groups, including patients, doctors, and pharmacies. This research informed the design of a user-friendly interface that is accessible to people of all ages and tech backgrounds. We made sure to include features like large buttons, simple navigation, and clear instructions to ensure that even the most tech-averse users could easily consult with doctors and order medications. To address privacy concerns, we implemented industry-standard encryption for all communications and data storage, ensuring compliance with regulations like HIPAA. We also built a robust backend infrastructure that could scale to meet the demands of a growing user base, ensuring that the app remained fast and responsive even during high-traffic periods. For the medicine delivery service, we developed APIs that allowed pharmacies to integrate their inventory systems directly with the app, ensuring real-time updates on medication availability. We also introduced a tracking system that allowed users to monitor the status of their medication deliveries in real-time. To ensure timely deliveries, we partnered with local pharmacies and delivery services, creating a reliable logistics network. The result was a seamless, end-to-end healthcare solution that meets the needs of both urban and rural populations, providing them with fast, affordable, and convenient access to healthcare services."
        }, {
            "_id": "3",
            "image": "https://i.ibb.co.com/fQR8F08/Image-9.png",
            "title": "The Future Lifestyle Platform",
            "typeOfBusiness": "Business, Creative",
            "relatedPictures3": ["crypto_pic1.jpg", "crypto_pic2.jpg", "crypto_pic3.jpg"],
            "description": "Cryptocurrencies and blockchain technology have revolutionized the financial world, offering users an entirely new way to engage with assets and digital services. The Future Lifestyle Platform is designed to capitalize on these innovations by bringing together a range of services under one ecosystem. Our platform aims to provide users with a single, unified space where they can manage cryptocurrencies, invest in blockchain-based assets, and engage with decentralized finance (DeFi) applications. The goal is to empower users to manage their financial and lifestyle needs within the same interface. With features like cryptocurrency wallets, investment trackers, DeFi integrations, and a marketplace for digital goods and services, the platform offers a holistic solution. Additionally, it is designed with an intuitive user interface, making it accessible for both tech-savvy users and newcomers. The platform is highly customizable, allowing users to tailor their experience based on their financial goals and interests. This positions it as a key player in the growing space of blockchain and crypto-based services. By combining diverse features into one cohesive experience, we are helping users to seamlessly integrate digital assets into their everyday lives.",

            "problems": "One of the key problems we identified before creating the Future Lifestyle Platform was the fragmentation of blockchain services. Users had to navigate between multiple apps and platforms just to manage their cryptocurrencies, track investments, and interact with DeFi projects. This lack of integration created a poor user experience and discouraged newcomers from adopting digital assets. Additionally, there was a significant knowledge gap when it came to understanding the complexities of managing crypto and DeFi portfolios. Many users, particularly beginners, found the jargon and technicalities overwhelming, which resulted in many potential investors shying away from the space. Furthermore, the volatility and security risks associated with cryptocurrencies were also concerns, as users feared the potential of losing their investments due to market fluctuations or hacking incidents. The lack of user-friendly and all-in-one solutions in the crypto space meant that users were left to piece together their experience through different platforms, which resulted in inefficiencies and increased security vulnerabilities. This highlighted the need for a centralized platform that could provide a streamlined, secure, and accessible solution.",

            "challenges": "Building the Future Lifestyle Platform posed several challenges, primarily due to the complexity of integrating multiple blockchain-based services into one user-friendly interface. One of the major challenges was ensuring the platform's security, particularly because it would be handling sensitive financial data and digital assets. Ensuring compliance with global regulatory frameworks for cryptocurrencies and blockchain-based services added another layer of complexity. Moreover, we needed to address the scalability of the platform, as the growing adoption of cryptocurrencies means that the platform needed to support a large and diverse user base without compromising performance. Another challenge was designing an intuitive user experience that would cater to both experienced crypto enthusiasts and beginners. Balancing the need for advanced features like DeFi integrations and sophisticated investment tracking tools with simplicity for novice users was a significant task. Additionally, keeping up with the fast pace of technological advancements in the blockchain space required continuous updates and improvements to the platform.",

            "ourSolution": "Our solution was to build a comprehensive and secure platform that integrates all key cryptocurrency services under one roof, simplifying the user experience while ensuring the highest levels of security. We implemented advanced encryption and multi-factor authentication to protect users' digital assets and personal data. The platform includes a customizable dashboard where users can manage their crypto portfolios, track investments, and interact with DeFi projects. To address the knowledge gap, we added an educational module that helps users understand the basics of cryptocurrencies, blockchain technology, and decentralized finance, making it easier for beginners to get started. Additionally, we partnered with leading security firms to audit the platform's infrastructure, ensuring it meets global security standards. Scalability was achieved by building the platform on a cloud-based infrastructure, allowing us to support a growing user base without sacrificing performance. By integrating APIs for popular cryptocurrency exchanges and DeFi platforms, we provided users with a seamless experience where they can buy, sell, and trade cryptocurrencies, as well as invest in digital assets, all in one place. Through continuous updates and user feedback, we are constantly improving the platform to meet the evolving needs of our users, positioning the Future Lifestyle Platform as a key solution in the blockchain ecosystem."
        }, {
            "_id": "4",
            "image": "https://i.ibb.co.com/hVzD7b7/Image-10.png",
            "title": "Venture Capital Business",
            "typeOfBusiness": "Corporate, Business",
            "relatedPictures3": ["venture_pic1.jpg", "venture_pic2.jpg", "venture_pic3.jpg"],
            "description": "The Venture Capital Business project focuses on the creation of a dynamic platform designed to revolutionize the way venture capital firms interact with both startups and investors. With the growing demand for more efficient capital deployment, the goal was to streamline the process by which investors discover, evaluate, and invest in promising startups. The platform offers a comprehensive suite of tools, including startup profiling, portfolio tracking, due diligence automation, and a collaboration space for investors to share insights and recommendations. The idea was to transform the traditionally fragmented venture capital ecosystem into a more interconnected and data-driven environment. Additionally, the platform provides startups with a way to showcase their potential to a larger pool of investors, thus increasing their chances of securing funding. The emphasis on usability and data visualization was key in helping stakeholders make informed decisions quickly and accurately. This venture capital platform not only enhances communication between startups and investors but also ensures that the entire lifecycle of investment is transparent, efficient, and accessible for all parties involved.",

            "problems": "Traditional venture capital businesses often struggle with outdated methods of investment tracking and decision-making, which are typically manual and time-consuming. One of the major issues in the venture capital industry is the lack of a centralized platform where investors can manage their portfolios, track startup performance, and collaborate with other investors in real-time. As a result, venture capital firms often face inefficiencies in evaluating potential investments and managing their existing ones. Another problem is that startups frequently find it difficult to connect with the right investors, as the current landscape is fragmented and network-dependent. Additionally, many small and emerging startups face challenges in securing funding due to their inability to effectively present their value proposition to investors in a structured and data-backed way. The result is often missed opportunities, inefficiencies in deal sourcing, and an overall lack of transparency within the investment lifecycle. The need for a more streamlined, data-driven approach to venture capital became clear, prompting the need for an innovative solution that could centralize the entire investment process.",

            "challenges": "The development of this platform presented several challenges. One of the main obstacles was creating a user experience that catered to two very different user groups: venture capital firms and startups. On the one hand, investors needed a tool that allowed them to make informed, data-driven decisions, while on the other hand, startups required a space to effectively present their business models and financials. Bridging the gap between these two groups and creating a platform that addressed both their needs required extensive research and user testing. Another challenge was building a scalable infrastructure that could handle vast amounts of financial data, perform analytics, and generate insights in real-time without compromising the performance of the platform. Ensuring data security and privacy was also a major concern, as the platform would handle sensitive financial and proprietary information from both startups and investors. The challenge of integrating various third-party APIs for financial data analysis, and structuring the platform for future technological upgrades, was another key issue that needed to be addressed. Lastly, ensuring regulatory compliance across different jurisdictions presented a unique challenge, especially as venture capital firms operate globally.",

            "ourSolution": "Our solution was to build a state-of-the-art platform that integrates all the necessary tools for venture capital firms and startups under one roof. The platform includes features such as automated deal flow, real-time portfolio tracking, financial performance analytics, and a collaborative space where investors can discuss potential opportunities. We implemented a powerful algorithm that helps match investors with startups that align with their investment criteria, thereby increasing the chances of successful funding. To address the issue of scalability, we built the platform on a cloud-based infrastructure, ensuring it can handle large volumes of data without sacrificing speed or performance. Security was enhanced through the use of encryption protocols and multi-factor authentication to protect user data and maintain confidentiality. Additionally, we introduced a dashboard that visualizes key performance indicators (KPIs) for startups, allowing investors to quickly assess the health and potential of an investment opportunity. To further support startups, we built in tools that help them prepare investor-ready profiles, making it easier for them to present their business case in a compelling and data-backed way. The platform also supports international regulatory compliance, enabling venture capital firms to operate across different regions without having to worry about legal hurdles. Overall, the platform has transformed the venture capital space by offering a centralized, data-driven, and secure solution for both investors and startups."
        }, {
            "_id": "5",
            "image": "https://i.ibb.co.com/HF3jN9n/Image-11.png",
            "title": "Stock Trading and Investing UX Design",
            "typeOfBusiness": "Startup, Corporate",
            "relatedPictures3": ["stock_pic1.jpg", "stock_pic2.jpg", "stock_pic3.jpg"],
            "description": "Stock trading platforms have become indispensable tools for investors, both novice and experienced, as they enable real-time trading and access to market data. However, with the increasing complexity of financial products and market trends, there is a growing need for platforms that simplify user interaction while providing advanced tools for analysis. This project focused on creating a seamless user experience for a stock trading and investing platform by prioritizing accessibility and intuitive navigation. The design emphasizes usability for all user levels, featuring a clean interface with easy access to key functions such as portfolio management, stock tracking, and real-time trading data. Additionally, the design incorporates elements that guide users through the decision-making process, offering insights, charts, and news that help users make informed trades. The platform also has responsive design capabilities, ensuring a consistent experience across devices. The goal was to create a platform that provides both simplicity for new investors and the depth required by experienced traders.",

            "problems": "One of the biggest issues with existing stock trading platforms is their complexity, which can be overwhelming for new users. Many platforms are cluttered with advanced features, making it difficult for users to navigate the interface and perform basic tasks such as buying or selling stocks. Additionally, these platforms often lack personalized guidance, leaving users to figure out the complexities of stock trading on their own. Another significant problem is the accessibility of critical information. Users may struggle to find real-time data, stock performance reports, and news feeds that are essential for making informed trading decisions. Moreover, the lack of a user-friendly mobile interface is a problem, as more users are relying on mobile devices for trading. A significant challenge is also the lack of personalization, as most platforms offer a one-size-fits-all solution, which fails to cater to the individual needs of different user segments, particularly novice investors who require a more educational approach.",

            "challenges": "The main challenge in designing a stock trading platform is creating an interface that balances simplicity with advanced functionality. Experienced traders require detailed market analysis tools, while new users need a straightforward interface that allows them to make trades without feeling overwhelmed. One of the biggest challenges was organizing complex data, such as real-time stock charts, financial news, and investment portfolios, in a way that was easily digestible. Additionally, incorporating educational resources for beginners without disrupting the experience for advanced users was a major challenge. Another key challenge was ensuring that the platform could handle high volumes of real-time data without sacrificing performance, especially during market peaks. Mobile optimization was also a critical challenge, as users needed the ability to perform all trading activities seamlessly across devices. Ensuring security and compliance with financial regulations while maintaining a fast and responsive user experience was another important aspect of the design challenge.",

            "ourSolution": "Our solution was to design a user interface that is both functional and accessible to a wide range of users. For new investors, we incorporated educational features, such as tooltips and step-by-step guides, which explain key trading concepts as they navigate the platform. We also introduced a simplified mode, which presents only the essential features, such as buying and selling stocks, to minimize confusion. For experienced traders, the platform includes advanced analytics, charting tools, and customizable dashboards that allow them to track their investments and monitor market trends in real time. To address the issue of accessibility, we implemented a responsive design that adapts seamlessly to both desktop and mobile devices. The platform integrates real-time data feeds and news updates directly into the dashboard, ensuring that users have access to the information they need without having to leave the interface. We also placed a strong emphasis on personalization, allowing users to customize their dashboards according to their preferences, whether they are focusing on specific stocks, news sources, or market sectors. Additionally, we ensured the platform complied with all financial regulations, and we implemented multi-factor authentication and encryption to protect user data and ensure secure transactions."
        }, {
            "_id": "6",
            "image": "https://i.ibb.co.com/BzRhF7r/Image-12.png",
            "title": "Review and Web Traffic Management",
            "typeOfBusiness": "Corporate, Business",
            "relatedPictures3": ["traffic_pic1.jpg", "traffic_pic2.jpg", "traffic_pic3.jpg"],
            "description": "In the digital era, managing online reviews and web traffic is critical for businesses aiming to maintain a positive reputation and optimize their online presence. For businesses that rely on customer feedback, reviews play a significant role in influencing new customers' purchasing decisions. A robust platform for review management enables businesses to monitor and respond to reviews effectively. This project involved designing a system that not only tracks reviews across multiple platforms but also analyzes the sentiment and provides insights on customer perceptions. Moreover, we integrated web traffic management tools that offer businesses a detailed understanding of their website visitors’ behavior, allowing for strategic improvements in their marketing and user engagement efforts. By combining both review management and web traffic analytics in one platform, we provided businesses with a comprehensive solution to boost their online presence and customer engagement. The goal was to streamline the management of customer feedback and enhance the user experience through data-driven insights and actionable solutions.",

            "problems": "One of the key issues businesses face is the lack of efficient tools to manage online reviews and customer feedback. Many companies rely on manual monitoring, which is time-consuming and often misses critical insights. Negative reviews, if not addressed promptly, can significantly damage a business's reputation. Another problem is the difficulty in interpreting the vast amount of data generated by web traffic. Businesses often struggle to identify trends in user behavior, leading to ineffective marketing strategies and poor customer retention. Additionally, the fragmentation of review sources, with customers leaving feedback on various platforms such as Google, Yelp, and social media, makes it challenging for businesses to respond in a timely and unified manner. Without the ability to track and analyze both reviews and web traffic data efficiently, businesses are left with an incomplete understanding of their online presence, which hampers growth and customer satisfaction.",

            "challenges": "Developing an integrated system that combines review management and web traffic analysis posed several challenges. First, we needed to design a platform capable of aggregating reviews from multiple sources in real-time while maintaining a simple and intuitive user interface. Another challenge was ensuring that the sentiment analysis algorithm could accurately interpret the context of customer reviews, including detecting sarcasm or mixed sentiments, which are often misinterpreted by automated systems. From a technical standpoint, ensuring that the platform could handle high volumes of web traffic data while providing real-time analytics without causing system slowdowns was a major challenge. Another significant challenge was ensuring compatibility with existing content management systems (CMS) and marketing tools that businesses use, allowing for seamless integration into their current workflows. Additionally, the platform needed to be scalable to accommodate the varying needs of small businesses to large corporations.",

            "ourSolution": "Our solution was to develop a comprehensive platform that offers both review management and web traffic analytics in one system. We implemented a real-time review aggregation tool that pulls in customer reviews from various platforms, including social media, and presents them in a single, easy-to-navigate dashboard. The platform also incorporates advanced sentiment analysis, powered by machine learning algorithms, which accurately categorizes customer feedback as positive, negative, or neutral, helping businesses prioritize responses. For web traffic management, we integrated tools that track visitor behavior, bounce rates, and conversion metrics, offering businesses deep insights into how customers interact with their websites. The platform includes customizable reports and automated notifications, ensuring businesses stay informed about critical changes in their online performance. To address the challenge of system integration, we made the platform compatible with popular CMS and marketing tools, allowing businesses to implement it without disrupting their existing operations. Furthermore, the platform is highly scalable, capable of meeting the needs of businesses of all sizes, from small local companies to large corporations."
        }, {
            "_id": "7",
            "image": "https://i.ibb.co.com/ZxxVTG7/Image-13.png",
            "title": "Design of the Year",
            "typeOfBusiness": "Business, Creative",
            "relatedPictures3": ["design_pic1.jpg", "design_pic2.jpg", "design_pic3.jpg"],
            "description": "The 'Design of the Year' project sought to create an innovative and trendsetting design that would not only meet current business needs but also inspire future design standards. This project emphasized creativity, usability, and adaptability across various platforms. By focusing on sleek aesthetics combined with functionality, we aimed to develop a design that appeals to both business and creative industries. The project included rigorous research into the latest design trends, user behavior, and technological advancements to ensure the design remains relevant for years to come. The final outcome was a visually stunning and highly responsive design that adapts to different devices, platforms, and user preferences. In addition to being aesthetically pleasing, the design also improved user engagement and business conversions, showcasing the perfect blend of form and function. This project set a new standard for digital design, offering a scalable solution that businesses can easily adapt and customize to fit their unique needs.",

            "problems": "One of the major problems faced during the project was the rapid evolution of design trends, which often makes certain design elements obsolete within a short period. Keeping up with these trends while ensuring that the design remains timeless and adaptable was a significant challenge. Additionally, there was a need to create a design that could work across different platforms and devices, such as desktops, mobile phones, and tablets, without compromising on user experience. Another problem was striking the right balance between creativity and functionality. Many creative designs often fail when it comes to usability, which can lead to a higher bounce rate and lower user satisfaction. Ensuring that the design was both visually striking and easy to navigate was critical for the success of this project. Lastly, ensuring that the design could be easily customized for different business needs without requiring extensive rework was another challenge we aimed to address.",

            "challenges": "The biggest challenge of the project was maintaining the delicate balance between creativity and functionality. While it's tempting to prioritize aesthetics, the design needed to be functional, offering users an intuitive and seamless experience across all devices. Another challenge was ensuring the design's longevity. Design trends come and go, and we wanted to create something that wouldn’t feel outdated after a year or two. This required extensive research into both current and emerging trends. Furthermore, the design needed to be versatile enough to accommodate businesses from various industries, each with unique branding and functional requirements. Another technical challenge was ensuring compatibility with various content management systems (CMS) and frameworks that businesses use. This required us to create a modular design system that could be easily integrated without requiring businesses to overhaul their entire infrastructure. Additionally, the design had to be lightweight and fast-loading to enhance performance, particularly on mobile devices, where users expect instant responses.",

            "ourSolution": "To address these challenges, we implemented a flexible, modular design system that allows businesses to customize the look and feel of their platforms without sacrificing usability. The design is responsive by nature, ensuring optimal performance across all devices and screen sizes. We used a combination of cutting-edge design tools and methodologies, such as atomic design principles, to ensure that the design elements are both scalable and reusable. Our team worked closely with UX experts to ensure that the design provides a seamless and intuitive experience for users. In terms of aesthetic longevity, we focused on minimalistic, clean lines that are unlikely to go out of style quickly. This approach also makes it easier for businesses to incorporate their own branding elements without disrupting the overall design. To ensure fast load times and high performance, we optimized the design by using lightweight assets and implementing best practices for web development. We also provided extensive documentation and tutorials to help businesses customize the design easily, ensuring that the solution remains scalable and future-proof."
        }, {
            "_id": "8",
            "image": "https://i.ibb.co.com/pyhqFnF/Image-14.png",
            "title": "Better Digital Banking",
            "typeOfBusiness": "Corporate, Creative",
            "relatedPictures3": ["banking_pic1.jpg", "banking_pic2.jpg", "banking_pic3.jpg"],
            "description": "The 'Better Digital Banking' project aimed to redefine how users interact with their financial institutions. In a world where digital transformation is reshaping various industries, the banking sector has lagged behind in providing user-friendly and engaging digital experiences. Our approach involved creating a platform that integrates advanced technologies with user-centric design principles. The platform features an intuitive interface that simplifies navigation and allows users to manage their finances with ease. From account management to budgeting tools and investment tracking, every aspect of the platform is designed to enhance user experience. We focused on providing comprehensive features while ensuring a secure and seamless experience for users. Our commitment was not only to meet regulatory standards but also to instill trust in users, ensuring they feel safe while conducting transactions. We engaged in extensive user testing to fine-tune the design and functionality, leading to a product that effectively addresses the evolving needs of modern banking customers.",

            "problems": "Traditional banking apps have often been criticized for their outdated interfaces and complicated navigation. Many users find these apps frustrating, leading to dissatisfaction and a lack of engagement. The primary problem we identified was that existing banking solutions often did not prioritize user experience. Instead, they were focused more on security and compliance, neglecting the need for intuitive design. Additionally, there was a significant gap in features that facilitate financial literacy and budgeting, which are essential for empowering users to manage their finances effectively. Users often felt overwhelmed by the complexity of financial products and struggled to access the information they needed. The challenge of integrating modern technology with legacy systems also posed a significant barrier, leading to inefficiencies in service delivery. As a result, customers frequently faced delays and poor service quality, which further eroded trust in their financial institutions.",

            "challenges": "One of the key challenges was modernizing the user experience while ensuring compliance with stringent regulatory requirements. Balancing innovation with security was crucial, as financial data is highly sensitive. Moreover, we had to ensure that the design catered to a diverse user base, including individuals with varying levels of tech-savviness. Another challenge was integrating the platform with existing banking infrastructure, which often involves outdated systems that do not easily accommodate modern functionalities. This required close collaboration with technical teams to develop a flexible architecture that could adapt to both current and future needs. Additionally, we faced the challenge of fostering user trust in digital banking solutions, which often requires overcoming skepticism associated with online financial transactions. To address this, we needed to focus on transparency, security features, and clear communication regarding data protection.",

            "ourSolution": "To tackle these challenges, we implemented a user-centered design approach that placed the customer at the heart of the development process. Our solution included creating a clean, intuitive interface that simplifies navigation and enhances user engagement. We conducted extensive user research and testing to gather feedback, ensuring the final product aligns with user needs and expectations. Our platform incorporates advanced security features such as biometric authentication and encryption to safeguard user data, reinforcing trust in the digital banking experience. To enhance financial literacy, we integrated educational resources and budgeting tools directly within the app, empowering users to make informed financial decisions. The platform's architecture was designed to be modular, allowing for seamless integration with existing banking systems while remaining adaptable for future upgrades. Through these efforts, we have created a robust digital banking solution that not only meets the demands of today's consumers but also sets a new standard for user experience in the financial sector."
        }

    ]



    const [activeTabIndex, setActiveTabIndex] = useState(0);

    const handleTabClick = (index) => {
        setActiveTabIndex(index);
    };






    return (
        <div >
            <Tabs>
                <TabList className="lg:flex items-center justify-between lg:w-[466px] mx-auto my-12">
                    {["All", "Bussiness", "Corporate", "Creative", "Startup"].map((tabName, index) => (
                        <Tab
                            key={index}
                            className="focus:outline-none cursor-pointer"
                            onClick={() => handleTabClick(index)}
                        >

                            <div className={`border border-[#E6E8F1] lg:h-11 flex justify-between  items-center gap-7 p-2 rounded-[4px] ${activeTabIndex === index ? 'text-white bg-violet-600' : 'text-[#6d7568]'}`}>
                                <button className={` p-2 rounded-md ${activeTabIndex === index ? 'text-white bg-violet-600' : 'text-[#6d7568]'}`}>{tabName}</button>
                            </div>
                        </Tab>
                    ))}

                </TabList>

                <TabPanel >
                    <div className='grid lg:grid-cols-2 gap-5'>
                        {
                            Portfolio.map((item) => (
                                <ProtfolioDetails key={item._id} item={item}></ProtfolioDetails>
                            ))
                        }
                    </div>
                </TabPanel>
                <TabPanel>
                    <h2>Any content 2</h2>
                </TabPanel>
            </Tabs>
        </div>
    );
};

export default MyTab;